version: '3.1'
services:
  jenkins:
      image: jenkins/jenkins
      ports: 
        - 8080:8080
        - 50000:50000

      container_name: jenkins
      privileged: true
      user: root
      volumes:
        - C:/Users/manue/Desktop/jenkins_home:/var/jenkins_home
      networks:
        - net 
networks:
  net: 